-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgR4S9ssaUB/6HNKh9
NAhKTZTrdP8VkHCigfLVq6AZ4pqgCgYIKoZIzj0DAQehRANCAARnn9wDHYOfKMTC
uAfqFonXvWq+h7GU3RuPweFnTwEf8iSkvq1+/Pv2+EBDObVgvrasiJg+yR+CFvKm
VfDYoab7
-----END PRIVATE KEY-----