name: sporty_groups
description: "Sport Groups helper"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.3.0
  font_awesome_flutter: ^10.8.0
  flutter_svg: ^2.0.17
  cached_network_image: ^3.2.0
  flutter_image_compress: ^2.4.0
  # Firebase dependencies
  sign_in_with_apple: ^6.1.4
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.4.3
  image_picker: ^1.0.0
  intl: ^0.20.2
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  url_launcher: ^6.3.1
  google_sign_in: ^6.2.2
  firebase_messaging: ^15.2.3
  flutter_local_notifications: ^18.0.1
  share_plus: ^10.1.4
  path_provider: ^2.0.11
  http: ^1.3.0
  # Other dependencies
  async: ^2.12.0
  fake_async: ^1.3.2
  leak_tracker: 10.0.8 # Use version 10.0.8 to avoid conflict with firebase_core
  material_color_utilities: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fallback_profile.png
    - assets/apple_logo.svg
    - assets/google_logo.png